### ISSUE TITLE
Authentication fails

### ISSUE THREAD

**Issue by tedstriker** [Raynerv/node-red-contrib-mqttssl#1]
Hi there,

I'm experiencing trouble connecting to the broker using name + password for authentication.
The credentials are alright, as I use them with other clients as well. Different ones (also working with other clients) don't work either. I tried that just to rule out possible ACL issues.
The broker I use is mosquitto 1.3.4 and Node-RED 0.10.4

Weird thing is: when I allow anonymous users the connection is established immediately.

Do you have a hint, where to look at to fix it?
Also username and password are not loaded, when I reconfigure the broker config node.

Any help is appreciated. Thank you.

best regards,
Ted

**Comment by adrianbro** [comment]
I am having the same issue
using latest version of node-red and apollo broker

**Comment by dmelpi** [comment]
same here with Node Red 0.10.6 and mosquitto 1.4.1

**Comment by Raynerv** [comment]
I'm guessing this has something to do with how the config is handled, perhaps due to changes in node-red. I might have a solution later this week

**Comment by tedstriker** [comment]
Hi Raynerv, could you figure out what the problem is already? If not, is there a way I/we can assist you?

**Comment by VirTERM** [comment]
I have similar problem, is this not related to SSL vs TLS?

**Comment by tedstriker** [comment]
The initially described error doesn't have anything to do with TLS vs. SSL - also the referenced pull request fixed it. I already got it up and running.

**Comment by Raynerv** [comment]
@tedstriker  Thanks alot for looking into this. I've merged your changes and released 0.0.5 to npm. I currently don't have a SSL-enabled broker to test this release on.  Can you confirm that this release works, before I close this issue?

**Comment by tedstriker** [comment]
@raynerv you're welcome. I already use it with NodeRED 0.10.6 and mosquito 1.4.2 TLS enabled. A positive response from a second person would be great.
A restart of node.js and a reinsertion of the mqttssl node might be necessary.

**Comment by VirTERM** [comment]
Actually,
it does not work for me. It authenticates but than gets disconnected right away (user name/pass based authentication).
Mosquitto 1.4.2 and NodeRed 0.10.6
Other mqtt clients from iOS, command line and Macos (mqtt.fx) connect without any problem

Wojtek

**Comment by tedstriker** [comment]
So authentication works fine so far, but you get kicked out afterwards?
The only thing that got changed is the way credentials are being saved in node red. When it comes to authorization / certificate validation etc. I haven't changed a thing. You might try test.mosquitto

**Comment by tedstriker** [comment]
So authentication works fine so far, but you get kicked out afterwards?
The only thing that got changed is the way credentials are being saved in node red. When it comes to authorization / certificate validation etc. I haven't changed a thing. You might try test.mosquitto

**Comment by tedstriker** [comment]
Sorry. I hit close by accident.
You might try test.mosquitto.org to narrow it down

**Comment by VirTERM** [comment]
I need to run more tests, but your authentication seems to be working as I can see in mosquito logs if I specify incorrect password.
I still can not connect, despite ANY other client can connect….

The message is now very verbose, basically:
Socket error on client node-red-ssl11, disconnecting.

**Comment by tedstriker** [comment]
I wish you good luck finding a solution - as far as I can tell, this issue seems fixed.
If necessary, you can open another issue.
